/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main.Formularios;

import Main.DAO.BaseDatos;
import Main.DAO.IUsuarioImpl;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import static Main.Formularios.Dashboard.content;
import java.sql.PreparedStatement;
/**
 *
 * @author Alice Sugar
 */
public class Menu extends javax.swing.JPanel {
    DefaultTableModel modelo=new DefaultTableModel();
    Statement ejecutor=null;
    Connection conn;
    BaseDatos base = new BaseDatos(); 
    IUsuarioImpl US = new IUsuarioImpl();
    
    protected void mostrartabla(){
    DefaultTableModel modelos = new DefaultTableModel();
    modelos.addColumn("ID");
    modelos.addColumn("Usuario");
    modelos.addColumn("Contrseña");
    modelos.addColumn("Nombre");
    modelos.addColumn("Apellido");
    modelos.addColumn("Privilegio");
    modelos.setRowCount(0);
    
    tbl_buscar.getColumnModel().getColumn(0).setPreferredWidth(10);
    tbl_buscar.getColumnModel().getColumn(1).setPreferredWidth(10);
    tbl_buscar.getColumnModel().getColumn(2).setPreferredWidth(10);
    tbl_buscar.getColumnModel().getColumn(3).setPreferredWidth(10);
    tbl_buscar.getColumnModel().getColumn(4).setPreferredWidth(10);
    tbl_buscar.getColumnModel().getColumn(5).setPreferredWidth(10);
    
    String query = "SELECT * FROM `usuarios`";
    
    String datos [] = new String[6];
    ResultSet rs;
  
    try{
       ejecutor=conn.createStatement();
       ejecutor.setQueryTimeout(20);
       rs=ejecutor.executeQuery(query);
       while(rs.next()==true){
           datos[0] = rs.getString("id_usuario");
           datos[1] = rs.getString("username");
           datos[2] = rs.getString("password");
           datos[3] = rs.getString("nombres");
           datos[4] = rs.getString("apellidos");
           datos[5] = rs.getString("privilegios");
           modelos.addRow(datos);
        }
       tbl_buscar.setModel(modelos);
       } catch(Exception e){
           
       }
}
       public void conectar(){
        conn=null;
        try{
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sistemaadministrativo?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "");
        } catch (Exception e){
            System.out.println(""+e.getMessage());
    }
  }
    /**
     * Creates new form Test
     */
    public Menu() {
        initComponents();
        conectar();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_buscar = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_buscar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Usuername", "Password", "Nombre", "Apellido", "Privilegios"
            }
        ));
        jScrollPane1.setViewportView(tbl_buscar);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 770, 420));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Usuarios");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        search.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        search.setForeground(new java.awt.Color(102, 102, 102));
        search.setBorder(null);
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 580, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator2.setPreferredSize(new java.awt.Dimension(250, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 610, 10));

        jPanel5.setBackground(new java.awt.Color(18, 90, 173));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Buscar");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel6)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 33, 90, -1));

        jPanel6.setBackground(new java.awt.Color(18, 90, 173));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel6MousePressed(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Actualizar Tabla");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 160, 30));

        jPanel7.setBackground(new java.awt.Color(18, 90, 173));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel7MousePressed(evt);
            }
        });
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Añadir");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 60, -1));

        add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 530, 110, 30));

        jPanel1.setBackground(new java.awt.Color(18, 90, 173));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Eliminar");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 80, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 530, 110, 30));

        jPanel2.setBackground(new java.awt.Color(18, 90, 173));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Detalles Avanzados");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 170, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 530, 190, 30));
    }// </editor-fold>//GEN-END:initComponents

        public void elimina(){
        int fila = tbl_buscar.getSelectedRow();
        String valor = tbl_buscar.getValueAt(fila, 0).toString();
        
        try {
            PreparedStatement elimina = conn.prepareStatement("DELETE FROM usuarios WHERE id_usuario='"+valor+"'");
            elimina.executeUpdate();
            mostrartablas();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e+ "No Se Ha Eliminado");
        }
        


}
    
    
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
    elimina();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MousePressed

        Reg p1 = new Reg();
        p1.setSize(790, 570);
        p1.setLocation(0,0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7MousePressed

    private void jPanel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MousePressed
        mostrartabla();
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MousePressed

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
        mostrartablas();
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MousePressed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed

        Mod p1 = new Mod();
        p1.setSize(790, 570);
        p1.setLocation(0,0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField search;
    private javax.swing.JTable tbl_buscar;
    // End of variables declaration//GEN-END:variables


    private void mostrartablas(){
    String busqueda = search.getText();
    DefaultTableModel modelos = new DefaultTableModel();
    modelos.addColumn("ID");
    modelos.addColumn("Username");
    modelos.addColumn("Contrseña");
    modelos.addColumn("Nombre");
    modelos.addColumn("Apellido");
    modelos.addColumn("Privilegio");
    modelos.setRowCount(0);
    tbl_buscar.setModel(modelos);
    
    tbl_buscar.getColumnModel().getColumn(0).setPreferredWidth(100);
    tbl_buscar.getColumnModel().getColumn(1).setPreferredWidth(100);
    tbl_buscar.getColumnModel().getColumn(2).setPreferredWidth(100);
    tbl_buscar.getColumnModel().getColumn(3).setPreferredWidth(100);
    tbl_buscar.getColumnModel().getColumn(4).setPreferredWidth(100);
    tbl_buscar.getColumnModel().getColumn(5).setPreferredWidth(100);

    
    String slq = "SELECT * FROM `usuarios` WHERE username LIKE '%"+busqueda+"%'";
    
    String datos [] = new String[2];
    
    try{
        
        base.sentencia = base.getConnection().createStatement();
        base.rs = base.sentencia.executeQuery(slq);
        
            while(base.rs.next()){
                datos[0]= base.rs.getString("id_usuario");
                datos[1]= base.rs.getString("username");
                modelos.addRow(datos);
            }
            
    tbl_buscar.setModel(modelos);
                    
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
    }   
  }
    
}
