/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main.Formularios;


import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import Main.DAO.IOrdenesImpl;
import Main.Modelos.Ordenes;
import static Main.Formularios.Dashboard1.content;



/**
 *
 * @author Alice Sugar
 */
public class Mod3A extends javax.swing.JPanel {

    public Mod3A() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        phone2 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        tbuscar = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        tbuscador = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1280, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        jLabel1.setText("Modificar Orden");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 340, 50));

        jLabel2.setText("Fecha de Culminación de Mantenimiento");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));

        t1.setForeground(new java.awt.Color(102, 102, 102));
        t1.setBorder(null);
        t1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t1MousePressed(evt);
            }
        });
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 260, 30));

        t2.setForeground(new java.awt.Color(102, 102, 102));
        t2.setBorder(null);
        t2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t2MousePressed(evt);
            }
        });
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 260, 30));

        t3.setForeground(new java.awt.Color(102, 102, 102));
        t3.setBorder(null);
        t3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t3MousePressed(evt);
            }
        });
        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 260, 30));

        t4.setForeground(new java.awt.Color(102, 102, 102));
        t4.setBorder(null);
        t4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t43MousePressed(evt);
            }
        });
        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t43ActionPerformed(evt);
            }
        });
        add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 260, 30));

        t5.setForeground(new java.awt.Color(102, 102, 102));
        t5.setToolTipText("");
        t5.setBorder(null);
        t5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t5MousePressed(evt);
            }
        });
        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });
        add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 260, 30));

        t6.setForeground(new java.awt.Color(102, 102, 102));
        t6.setBorder(null);
        t6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t6MousePressed(evt);
            }
        });
        t6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t6ActionPerformed(evt);
            }
        });
        add(t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 260, 30));

        t7.setForeground(new java.awt.Color(102, 102, 102));
        t7.setBorder(null);
        t7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t7MousePressed(evt);
            }
        });
        t7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t7ActionPerformed(evt);
            }
        });
        add(t7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 260, 30));

        jLabel3.setText("Fecha de Incio de Mantenimiento");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 260, 10));

        jSeparator2.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator2.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 260, 10));

        jSeparator5.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator5.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 10, 380));

        jLabel12.setText("Tipo de Servicio Realizado");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, -1, -1));

        jSeparator11.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator11.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 260, 10));

        jSeparator12.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator12.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 260, 10));

        jLabel13.setText("Fecha de Registro");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator3.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 260, 10));

        jLabel14.setText("ID de Empresa");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        phone2.setForeground(new java.awt.Color(102, 102, 102));
        phone2.setBorder(null);
        phone2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                phone2MousePressed(evt);
            }
        });
        phone2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone2ActionPerformed(evt);
            }
        });
        add(phone2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 260, 30));

        jSeparator4.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator4.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 260, 10));

        jLabel15.setText("Tipo de Servicio Realizado");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, -1, -1));

        jSeparator6.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator6.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 260, 10));

        jLabel16.setText("ID  Empleado");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jSeparator7.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator7.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 560, 10));

        jLabel17.setText("Numero de Orden a Buscar");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        tbuscar.setBackground(new java.awt.Color(51, 102, 255));
        tbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbuscarMouseReleased(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Buscar");

        javax.swing.GroupLayout tbuscarLayout = new javax.swing.GroupLayout(tbuscar);
        tbuscar.setLayout(tbuscarLayout);
        tbuscarLayout.setHorizontalGroup(
            tbuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tbuscarLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(21, 21, 21))
        );
        tbuscarLayout.setVerticalGroup(
            tbuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tbuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(tbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 100, 40));

        tbuscador.setBorder(null);
        add(tbuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 560, 30));

        jSeparator13.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator13.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 260, -1));

        jLabel19.setText("Numero Orden");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t5ActionPerformed

    private void t5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t5MousePressed
       
    }//GEN-LAST:event_t5MousePressed

    private void t6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t6ActionPerformed

    private void t6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t6MousePressed

        // TODO add your handling code here:
    }//GEN-LAST:event_t6MousePressed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void t2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2MousePressed

    private void t7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t7ActionPerformed
        if(t7.getText().equals("Ingrese la Empresa"))
        t7.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_t7ActionPerformed

    private void t7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t7MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t7MousePressed

    private void t3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3MousePressed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void phone2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phone2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_phone2MousePressed

    private void phone2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phone2ActionPerformed

    private void t43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t43ActionPerformed

    private void t43MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t43MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t43MousePressed

    private void tbuscarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbuscarMouseReleased
        IOrdenesImpl io = new IOrdenesImpl();
        Ordenes o = io.listarOrdenes(tbuscador.getText());
        t1.setText(o.getId_orden());
        t2.setText(o.getFecha());
        t3.setText(o.getId_empresa());
        t4.setText(o.getId_empl());
        t5.setText(o.getFechainc());
        t6.setText(o.getFechafn());
        t7.setText(o.getTiporevis());
        // TODO add your handling code here:
    }//GEN-LAST:event_tbuscarMouseReleased

    private void t1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1MousePressed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField phone2;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField tbuscador;
    private javax.swing.JPanel tbuscar;
    // End of variables declaration//GEN-END:variables
}
