/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main.Formularios;


import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import Main.DAO.IEmpresaImpl;
import Main.Modelos.Empresa;
import static Main.Formularios.Dashboard.content;


/**
 *
 * @author Alice Sugar
 */
public class Reg1 extends javax.swing.JPanel {

    public Reg1() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fecha = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        rif = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        surcursal = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        ubequip = new javax.swing.JTextField();
        fechastar = new javax.swing.JTextField();
        fechaend = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1280, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        jLabel1.setText("Registrar nuevo Cliente");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 230, 50));

        jLabel2.setText("Empresa");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        fecha.setForeground(new java.awt.Color(102, 102, 102));
        fecha.setToolTipText("");
        fecha.setBorder(null);
        fecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fechaMousePressed(evt);
            }
        });
        fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaActionPerformed(evt);
            }
        });
        add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 260, 30));

        name.setForeground(new java.awt.Color(102, 102, 102));
        name.setBorder(null);
        name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nameMousePressed(evt);
            }
        });
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 260, 30));

        phone.setForeground(new java.awt.Color(102, 102, 102));
        phone.setBorder(null);
        phone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                phoneMousePressed(evt);
            }
        });
        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 260, 30));

        rif.setForeground(new java.awt.Color(102, 102, 102));
        rif.setBorder(null);
        rif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rifMousePressed(evt);
            }
        });
        rif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rifActionPerformed(evt);
            }
        });
        add(rif, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 260, 30));

        city.setForeground(new java.awt.Color(102, 102, 102));
        city.setBorder(null);
        city.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cityMousePressed(evt);
            }
        });
        city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityActionPerformed(evt);
            }
        });
        add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 260, 30));

        surcursal.setForeground(new java.awt.Color(102, 102, 102));
        surcursal.setBorder(null);
        surcursal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                surcursalMousePressed(evt);
            }
        });
        surcursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surcursalActionPerformed(evt);
            }
        });
        add(surcursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 260, 30));

        email.setForeground(new java.awt.Color(102, 102, 102));
        email.setBorder(null);
        email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                emailMousePressed(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 260, 30));

        ubequip.setForeground(new java.awt.Color(102, 102, 102));
        ubequip.setToolTipText("");
        ubequip.setBorder(null);
        ubequip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ubequipMousePressed(evt);
            }
        });
        ubequip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubequipActionPerformed(evt);
            }
        });
        add(ubequip, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 260, 30));

        fechastar.setForeground(new java.awt.Color(102, 102, 102));
        fechastar.setBorder(null);
        fechastar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fechastarMousePressed(evt);
            }
        });
        fechastar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechastarActionPerformed(evt);
            }
        });
        add(fechastar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 260, 30));

        fechaend.setForeground(new java.awt.Color(102, 102, 102));
        fechaend.setBorder(null);
        fechaend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fechaendMousePressed(evt);
            }
        });
        fechaend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaendActionPerformed(evt);
            }
        });
        add(fechaend, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 260, 30));

        jLabel3.setText("Fecha");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 260, 10));

        jSeparator2.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator2.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 260, 10));

        jSeparator3.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator3.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 260, 10));

        jSeparator4.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator4.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 260, 10));

        jSeparator5.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator5.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 10, 460));

        jLabel4.setText("RIF");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 20, -1));

        jLabel5.setText("Ciudad");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabel6.setText("Sucursal");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        jSeparator6.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator6.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 260, 10));

        jSeparator7.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator7.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 260, 10));

        jSeparator8.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator8.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 260, 10));

        jLabel7.setText("Email");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));

        jLabel8.setText("Ubicación del Equipo");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, -1));

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Registrar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, 210, 50));

        jLabel10.setText("Fin del Mantenimiento");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, -1));

        jSeparator9.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator9.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 260, 10));

        jLabel11.setText("Inicio del Mantenimiento");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, -1, -1));

        jSeparator10.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator10.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 260, 10));

        jLabel12.setText("Telefono");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jSeparator11.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator11.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 260, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaActionPerformed

    private void fechaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechaMousePressed
       
    }//GEN-LAST:event_fechaMousePressed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void nameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameMousePressed

        // TODO add your handling code here:
    }//GEN-LAST:event_nameMousePressed

    private void rifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rifActionPerformed

    private void rifMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rifMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_rifMousePressed

    private void cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityActionPerformed

    private void cityMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cityMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityMousePressed

    private void ubequipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubequipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubequipActionPerformed

    private void ubequipMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ubequipMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubequipMousePressed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void emailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailMousePressed

    private void surcursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surcursalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surcursalActionPerformed

    private void surcursalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_surcursalMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_surcursalMousePressed

    private void fechaendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaendActionPerformed

    private void fechaendMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechaendMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaendMousePressed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        Empresa e = new Empresa(rif.getText(), phone.getText(), name.getText(), city.getText(), surcursal.getText(), email.getText(), ubequip.getText());
        IEmpresaImpl ie = new IEmpresaImpl();
        ie.agregarEmpresa(e);
        JOptionPane.showMessageDialog(this, "Acción Completada");
        
        Menu1 p1 = new Menu1();
        p1.setSize(790, 570);
        p1.setLocation(0,0);
        
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
// TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MousePressed

    private void fechastarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fechastarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechastarMousePressed

    private void fechastarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechastarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechastarActionPerformed

    private void phoneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phoneMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneMousePressed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        if(phone.getText().equals("Ingrese la Empresa"))
        phone.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField city;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fecha;
    private javax.swing.JTextField fechaend;
    private javax.swing.JTextField fechastar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField rif;
    private javax.swing.JTextField surcursal;
    private javax.swing.JTextField ubequip;
    // End of variables declaration//GEN-END:variables
}
