/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main.Formularios;

import Main.DAO.IRevisionesImpl;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;

import static Main.Formularios.Dashboard2.content;
import Main.Modelos.Revisiones;


/**
 *
 * @author Alice Sugar
 */
public class Reg2 extends javax.swing.JPanel {

    public Reg2() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        t8 = new javax.swing.JTextField();
        t9 = new javax.swing.JTextField();
        t10 = new javax.swing.JTextField();
        t11 = new javax.swing.JTextField();
        t12 = new javax.swing.JTextField();
        t13 = new javax.swing.JTextField();
        t14 = new javax.swing.JTextField();
        t15 = new javax.swing.JTextField();
        t16 = new javax.swing.JTextField();
        t17 = new javax.swing.JTextField();
        t18 = new javax.swing.JTextField();
        t19 = new javax.swing.JTextField();
        t20 = new javax.swing.JTextField();
        t21 = new javax.swing.JTextField();
        t22 = new javax.swing.JTextField();
        t23 = new javax.swing.JTextField();
        t24 = new javax.swing.JTextField();
        t25 = new javax.swing.JTextField();
        t26 = new javax.swing.JTextField();
        t27 = new javax.swing.JTextField();
        t28 = new javax.swing.JTextField();
        t29 = new javax.swing.JTextField();
        t30 = new javax.swing.JTextField();
        t31 = new javax.swing.JTextField();
        t32 = new javax.swing.JTextField();
        t33 = new javax.swing.JTextField();
        t34 = new javax.swing.JTextField();
        t35 = new javax.swing.JTextField();
        t36 = new javax.swing.JTextField();
        t37 = new javax.swing.JTextField();
        t38 = new javax.swing.JTextField();
        t39 = new javax.swing.JTextField();
        t40 = new javax.swing.JTextField();
        t41 = new javax.swing.JTextField();
        t42 = new javax.swing.JTextField();
        t43 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jSeparator19 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jSeparator20 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jSeparator21 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jSeparator22 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        jSeparator23 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jSeparator24 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        jSeparator25 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        jSeparator26 = new javax.swing.JSeparator();
        jLabel28 = new javax.swing.JLabel();
        jSeparator27 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        jSeparator28 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        jSeparator29 = new javax.swing.JSeparator();
        jLabel31 = new javax.swing.JLabel();
        jSeparator30 = new javax.swing.JSeparator();
        jLabel32 = new javax.swing.JLabel();
        jSeparator31 = new javax.swing.JSeparator();
        jLabel33 = new javax.swing.JLabel();
        jSeparator32 = new javax.swing.JSeparator();
        jLabel34 = new javax.swing.JLabel();
        jSeparator33 = new javax.swing.JSeparator();
        jLabel35 = new javax.swing.JLabel();
        jSeparator34 = new javax.swing.JSeparator();
        jLabel36 = new javax.swing.JLabel();
        jSeparator35 = new javax.swing.JSeparator();
        jLabel37 = new javax.swing.JLabel();
        jSeparator36 = new javax.swing.JSeparator();
        jLabel38 = new javax.swing.JLabel();
        jSeparator37 = new javax.swing.JSeparator();
        jLabel39 = new javax.swing.JLabel();
        jSeparator38 = new javax.swing.JSeparator();
        jLabel40 = new javax.swing.JLabel();
        jSeparator39 = new javax.swing.JSeparator();
        jLabel41 = new javax.swing.JLabel();
        jSeparator40 = new javax.swing.JSeparator();
        jLabel42 = new javax.swing.JLabel();
        jSeparator41 = new javax.swing.JSeparator();
        jLabel43 = new javax.swing.JLabel();
        jSeparator42 = new javax.swing.JSeparator();
        jLabel44 = new javax.swing.JLabel();
        jSeparator43 = new javax.swing.JSeparator();
        jLabel45 = new javax.swing.JLabel();
        jSeparator44 = new javax.swing.JSeparator();
        jLabel46 = new javax.swing.JLabel();
        jSeparator45 = new javax.swing.JSeparator();
        jLabel47 = new javax.swing.JLabel();
        jSeparator46 = new javax.swing.JSeparator();
        jLabel48 = new javax.swing.JLabel();
        jSeparator47 = new javax.swing.JSeparator();
        jLabel49 = new javax.swing.JLabel();
        jSeparator48 = new javax.swing.JSeparator();
        jLabel50 = new javax.swing.JLabel();
        jSeparator50 = new javax.swing.JSeparator();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator53 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator54 = new javax.swing.JSeparator();
        jSeparator51 = new javax.swing.JSeparator();
        jLabel54 = new javax.swing.JLabel();
        jSeparator55 = new javax.swing.JSeparator();
        jLabel55 = new javax.swing.JLabel();
        jSeparator56 = new javax.swing.JSeparator();
        jLabel56 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1280, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(700, 570));
        jPanel2.setPreferredSize(new java.awt.Dimension(790, 1600));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 21)); // NOI18N
        jLabel1.setText("Modificar nuevo Registro");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 270, 20));

        t1.setForeground(new java.awt.Color(102, 102, 102));
        t1.setBorder(null);
        t1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t1MousePressed(evt);
            }
        });
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        jPanel2.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 260, 30));

        t2.setForeground(new java.awt.Color(102, 102, 102));
        t2.setBorder(null);
        t2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t2MousePressed(evt);
            }
        });
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        jPanel2.add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 260, 30));

        t3.setForeground(new java.awt.Color(102, 102, 102));
        t3.setBorder(null);
        t3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t3MousePressed(evt);
            }
        });
        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        jPanel2.add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 260, 30));

        t4.setForeground(new java.awt.Color(102, 102, 102));
        t4.setBorder(null);
        t4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t4MousePressed(evt);
            }
        });
        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });
        jPanel2.add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 260, 30));

        t5.setForeground(new java.awt.Color(102, 102, 102));
        t5.setBorder(null);
        t5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t5MousePressed(evt);
            }
        });
        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });
        jPanel2.add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 260, 30));

        t6.setForeground(new java.awt.Color(102, 102, 102));
        t6.setBorder(null);
        t6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t6MousePressed(evt);
            }
        });
        t6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t6ActionPerformed(evt);
            }
        });
        jPanel2.add(t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 260, 30));

        t7.setForeground(new java.awt.Color(102, 102, 102));
        t7.setBorder(null);
        t7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t7MousePressed(evt);
            }
        });
        t7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t7ActionPerformed(evt);
            }
        });
        jPanel2.add(t7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 260, 30));

        t8.setForeground(new java.awt.Color(102, 102, 102));
        t8.setBorder(null);
        t8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t8MousePressed(evt);
            }
        });
        t8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t8ActionPerformed(evt);
            }
        });
        jPanel2.add(t8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 260, 30));

        t9.setForeground(new java.awt.Color(102, 102, 102));
        t9.setBorder(null);
        t9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t9MousePressed(evt);
            }
        });
        t9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t9ActionPerformed(evt);
            }
        });
        jPanel2.add(t9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 260, 30));

        t10.setForeground(new java.awt.Color(102, 102, 102));
        t10.setBorder(null);
        t10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t10MousePressed(evt);
            }
        });
        t10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t10ActionPerformed(evt);
            }
        });
        jPanel2.add(t10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 670, 260, 30));

        t11.setForeground(new java.awt.Color(102, 102, 102));
        t11.setBorder(null);
        t11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t11MousePressed(evt);
            }
        });
        t11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t11ActionPerformed(evt);
            }
        });
        jPanel2.add(t11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 730, 260, 30));

        t12.setForeground(new java.awt.Color(102, 102, 102));
        t12.setBorder(null);
        t12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t12MousePressed(evt);
            }
        });
        t12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t12ActionPerformed(evt);
            }
        });
        jPanel2.add(t12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 800, 260, 30));

        t13.setForeground(new java.awt.Color(102, 102, 102));
        t13.setBorder(null);
        t13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t13MousePressed(evt);
            }
        });
        t13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t13ActionPerformed(evt);
            }
        });
        jPanel2.add(t13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 870, 260, 30));

        t14.setForeground(new java.awt.Color(102, 102, 102));
        t14.setBorder(null);
        t14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t14MousePressed(evt);
            }
        });
        t14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t14ActionPerformed(evt);
            }
        });
        jPanel2.add(t14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 940, 260, 30));

        t15.setForeground(new java.awt.Color(102, 102, 102));
        t15.setBorder(null);
        t15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t15MousePressed(evt);
            }
        });
        t15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t15ActionPerformed(evt);
            }
        });
        jPanel2.add(t15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1000, 260, 30));

        t16.setForeground(new java.awt.Color(102, 102, 102));
        t16.setBorder(null);
        t16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t16MousePressed(evt);
            }
        });
        t16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t16ActionPerformed(evt);
            }
        });
        jPanel2.add(t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1060, 260, 30));

        t17.setForeground(new java.awt.Color(102, 102, 102));
        t17.setBorder(null);
        t17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t17MousePressed(evt);
            }
        });
        t17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t17ActionPerformed(evt);
            }
        });
        jPanel2.add(t17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1130, 260, 30));

        t18.setForeground(new java.awt.Color(102, 102, 102));
        t18.setBorder(null);
        t18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t18MousePressed(evt);
            }
        });
        t18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t18ActionPerformed(evt);
            }
        });
        jPanel2.add(t18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1190, 260, 30));

        t19.setForeground(new java.awt.Color(102, 102, 102));
        t19.setBorder(null);
        t19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t19MousePressed(evt);
            }
        });
        t19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t19ActionPerformed(evt);
            }
        });
        jPanel2.add(t19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1260, 260, 30));

        t20.setForeground(new java.awt.Color(102, 102, 102));
        t20.setBorder(null);
        t20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t20MousePressed(evt);
            }
        });
        t20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t20ActionPerformed(evt);
            }
        });
        jPanel2.add(t20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1330, 260, 30));

        t21.setForeground(new java.awt.Color(102, 102, 102));
        t21.setBorder(null);
        t21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t21MousePressed(evt);
            }
        });
        t21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t21ActionPerformed(evt);
            }
        });
        jPanel2.add(t21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1390, 260, 30));

        t22.setForeground(new java.awt.Color(102, 102, 102));
        t22.setBorder(null);
        t22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t22MousePressed(evt);
            }
        });
        t22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t22ActionPerformed(evt);
            }
        });
        jPanel2.add(t22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1460, 260, 30));

        t23.setForeground(new java.awt.Color(102, 102, 102));
        t23.setBorder(null);
        t23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t23MousePressed(evt);
            }
        });
        t23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t23ActionPerformed(evt);
            }
        });
        jPanel2.add(t23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1530, 260, 30));

        t24.setForeground(new java.awt.Color(102, 102, 102));
        t24.setBorder(null);
        t24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t24MousePressed(evt);
            }
        });
        t24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t24ActionPerformed(evt);
            }
        });
        jPanel2.add(t24, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 260, 30));

        t25.setForeground(new java.awt.Color(102, 102, 102));
        t25.setBorder(null);
        t25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t25MousePressed(evt);
            }
        });
        t25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t25ActionPerformed(evt);
            }
        });
        jPanel2.add(t25, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 260, 30));

        t26.setForeground(new java.awt.Color(102, 102, 102));
        t26.setBorder(null);
        t26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t26MousePressed(evt);
            }
        });
        t26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t26ActionPerformed(evt);
            }
        });
        jPanel2.add(t26, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 260, 30));

        t27.setForeground(new java.awt.Color(102, 102, 102));
        t27.setBorder(null);
        t27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t27MousePressed(evt);
            }
        });
        t27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t27ActionPerformed(evt);
            }
        });
        jPanel2.add(t27, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 260, 30));

        t28.setForeground(new java.awt.Color(102, 102, 102));
        t28.setBorder(null);
        t28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t28MousePressed(evt);
            }
        });
        t28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t28ActionPerformed(evt);
            }
        });
        jPanel2.add(t28, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 260, 30));

        t29.setForeground(new java.awt.Color(102, 102, 102));
        t29.setBorder(null);
        t29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t29MousePressed(evt);
            }
        });
        t29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t29ActionPerformed(evt);
            }
        });
        jPanel2.add(t29, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 260, 30));

        t30.setForeground(new java.awt.Color(102, 102, 102));
        t30.setBorder(null);
        t30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t30MousePressed(evt);
            }
        });
        t30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t30ActionPerformed(evt);
            }
        });
        jPanel2.add(t30, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, 260, 30));

        t31.setForeground(new java.awt.Color(102, 102, 102));
        t31.setBorder(null);
        t31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t31MousePressed(evt);
            }
        });
        t31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t31ActionPerformed(evt);
            }
        });
        jPanel2.add(t31, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 550, 260, 30));

        t32.setForeground(new java.awt.Color(102, 102, 102));
        t32.setBorder(null);
        t32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t32MousePressed(evt);
            }
        });
        t32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t32ActionPerformed(evt);
            }
        });
        jPanel2.add(t32, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 610, 260, 30));

        t33.setForeground(new java.awt.Color(102, 102, 102));
        t33.setBorder(null);
        t33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t33MousePressed(evt);
            }
        });
        t33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t33ActionPerformed(evt);
            }
        });
        jPanel2.add(t33, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 680, 260, 30));

        t34.setForeground(new java.awt.Color(102, 102, 102));
        t34.setBorder(null);
        t34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t34MousePressed(evt);
            }
        });
        t34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t34ActionPerformed(evt);
            }
        });
        jPanel2.add(t34, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 750, 260, 30));

        t35.setForeground(new java.awt.Color(102, 102, 102));
        t35.setBorder(null);
        t35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t35MousePressed(evt);
            }
        });
        t35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t35ActionPerformed(evt);
            }
        });
        jPanel2.add(t35, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 820, 260, 30));

        t36.setForeground(new java.awt.Color(102, 102, 102));
        t36.setBorder(null);
        t36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t36MousePressed(evt);
            }
        });
        t36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t36ActionPerformed(evt);
            }
        });
        jPanel2.add(t36, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 880, 260, 30));

        t37.setForeground(new java.awt.Color(102, 102, 102));
        t37.setBorder(null);
        t37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t37MousePressed(evt);
            }
        });
        t37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t37ActionPerformed(evt);
            }
        });
        jPanel2.add(t37, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 940, 260, 30));

        t38.setForeground(new java.awt.Color(102, 102, 102));
        t38.setBorder(null);
        t38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t38MousePressed(evt);
            }
        });
        t38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t38ActionPerformed(evt);
            }
        });
        jPanel2.add(t38, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 1010, 260, 30));

        t39.setForeground(new java.awt.Color(102, 102, 102));
        t39.setBorder(null);
        t39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t39MousePressed(evt);
            }
        });
        t39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t39ActionPerformed(evt);
            }
        });
        jPanel2.add(t39, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 1070, 260, 30));

        t40.setForeground(new java.awt.Color(102, 102, 102));
        t40.setBorder(null);
        t40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t40MousePressed(evt);
            }
        });
        t40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t40ActionPerformed(evt);
            }
        });
        jPanel2.add(t40, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 1140, 260, 30));

        t41.setForeground(new java.awt.Color(102, 102, 102));
        t41.setBorder(null);
        t41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t41MousePressed(evt);
            }
        });
        t41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t41ActionPerformed(evt);
            }
        });
        jPanel2.add(t41, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 1210, 260, 30));

        t42.setForeground(new java.awt.Color(102, 102, 102));
        t42.setBorder(null);
        t42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                t42MousePressed(evt);
            }
        });
        t42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t42ActionPerformed(evt);
            }
        });
        jPanel2.add(t42, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 1300, 260, 30));

        t43.setBackground(new java.awt.Color(243, 243, 243));
        t43.setBorder(null);
        t43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t43ActionPerformed(evt);
            }
        });
        jPanel2.add(t43, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 1370, 280, 70));

        jSeparator5.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator5.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 10, 1440));

        jLabel6.setText("P. Descarga");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, -1));

        jSeparator6.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator6.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 260, 10));

        jSeparator13.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator13.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 260, 10));

        jLabel15.setText("Tecnico");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jSeparator14.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator14.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 260, 10));

        jLabel16.setText("Tipo Equipo");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jSeparator15.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator15.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 260, 10));

        jLabel17.setText("Marca de Equipo");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        jSeparator16.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator16.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 260, 10));

        jLabel18.setText("Capacidad de Equipo");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));

        jSeparator17.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator17.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 260, 10));

        jLabel19.setText("Voltaje de Placa");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));

        jSeparator18.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator18.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, 260, 10));

        jLabel20.setText("Voltaje de Consumo");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, -1, -1));

        jSeparator19.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator19.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 700, 260, 10));

        jLabel21.setText("Amperaje de Placa");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 650, -1, -1));

        jSeparator20.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator20.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 760, 260, 10));

        jLabel22.setText("Amperaje L1");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 710, -1, -1));

        jSeparator21.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator21.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 830, 260, 10));

        jLabel23.setText("Amperaje L2");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 780, -1, -1));

        jSeparator22.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator22.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 900, 260, 10));

        jLabel24.setText("Amperaje L3");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 850, -1, -1));

        jSeparator23.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator23.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 970, 260, 10));

        jLabel25.setText("Temperatura Ambiente");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 920, -1, -1));

        jSeparator24.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator24.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1030, 260, 10));

        jLabel26.setText("Tipo de Refrigerante");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 980, -1, -1));

        jSeparator25.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator25.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1090, 260, 10));

        jLabel27.setText("Modelo de Evaporadora");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1040, -1, -1));

        jSeparator26.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator26.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1160, 260, 10));

        jLabel28.setText("Serial de Evaporadora");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1110, -1, -1));

        jSeparator27.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator27.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1220, 260, 10));

        jLabel29.setText("Voltaje de Placa");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1170, -1, -1));

        jSeparator28.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator28.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1290, 260, 10));

        jLabel30.setText("Voltaje de Consumo");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1240, -1, -1));

        jSeparator29.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator29.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1360, 260, 10));

        jLabel31.setText("Amperaje de Placa");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1310, -1, -1));

        jSeparator30.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator30.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1420, 260, 10));

        jLabel32.setText("Amperaje L1");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1370, -1, -1));

        jSeparator31.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator31.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1490, 260, 10));

        jLabel33.setText("Amperaje L2");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1440, -1, -1));

        jSeparator32.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator32.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1560, 260, 10));

        jLabel34.setText("Amperaje L3");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1510, -1, -1));

        jSeparator33.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator33.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator33, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 260, 10));

        jLabel35.setText("Modelo de Condensadora");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, -1, -1));

        jSeparator34.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator34.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator34, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 260, 10));

        jLabel36.setText("Serial de Condensadora");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, -1, -1));

        jSeparator35.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator35.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator35, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 260, 10));

        jLabel37.setText("Funcionamiento");
        jPanel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, -1, -1));

        jSeparator36.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator36.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator36, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 260, 10));

        jLabel38.setText("Carga de Refrigerante");
        jPanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, -1, -1));

        jSeparator37.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator37.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator37, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 510, 260, 10));

        jLabel39.setText("Sepertin Condensadora");
        jPanel2.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, -1, -1));

        jSeparator38.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator38.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator38, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 580, 260, 10));

        jLabel40.setText("Serpetin Evaporadora");
        jPanel2.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 530, -1, -1));

        jSeparator39.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator39.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator39, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 640, 260, 10));

        jLabel41.setText("Filtro");
        jPanel2.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 590, -1, -1));

        jSeparator40.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator40.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator40, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 710, 260, 10));

        jLabel42.setText("Ventilador Condensadora");
        jPanel2.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 660, -1, -1));

        jSeparator41.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator41.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator41, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 780, 260, 10));

        jLabel43.setText("ventilador Evaporadora");
        jPanel2.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 730, -1, -1));

        jSeparator42.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator42.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator42, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 850, 260, 10));

        jLabel44.setText("Compresor");
        jPanel2.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 800, -1, -1));

        jSeparator43.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator43.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator43, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 910, 260, 10));

        jLabel45.setText("Tubo de Escape");
        jPanel2.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 860, -1, -1));

        jSeparator44.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator44.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator44, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 970, 260, 10));

        jLabel46.setText("Tubo Aislado");
        jPanel2.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 920, -1, -1));

        jSeparator45.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator45.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator45, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 1040, 260, 10));

        jLabel47.setText("Tubo de Soporte");
        jPanel2.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 990, -1, -1));

        jSeparator46.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator46.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator46, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 1100, 260, 10));

        jLabel48.setText("Breakers");
        jPanel2.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 1050, -1, -1));

        jSeparator47.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator47.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator47, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 1170, 260, 10));

        jLabel49.setText("Protector");
        jPanel2.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 1120, -1, -1));

        jSeparator48.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator48.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator48, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 1240, 260, 10));

        jLabel50.setText("Cableado Electrico");
        jPanel2.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 1190, -1, -1));

        jSeparator50.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator50.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator50, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 260, 10));

        jLabel52.setText("ID Empresa");
        jPanel2.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel53.setText("Nota");
        jPanel2.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 1350, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("GUARDAR");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("GUARDAR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 1520, 170, 50));

        jSeparator53.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator53.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator53, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 1440, 280, 10));

        jLabel3.setText("Lugar de Trabajo");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 1270, -1, -1));

        jSeparator54.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator54.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator54, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 1330, 280, 10));

        jSeparator51.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator51.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator51, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 260, 10));

        jLabel54.setText("Fecha de Revisión");
        jPanel2.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jSeparator55.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator55.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator55, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 260, 10));

        jLabel55.setText("P. Succión");
        jPanel2.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));

        jSeparator56.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator56.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel2.add(jSeparator56, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 260, 10));

        jLabel56.setText("Numero Revision");
        jPanel2.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jScrollPane1.setViewportView(jPanel2);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 570));
    }// </editor-fold>//GEN-END:initComponents

    private void t43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t43ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void t3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3MousePressed

    private void t12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t12ActionPerformed

    private void t12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t12MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t12MousePressed

    private void t40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t40ActionPerformed

    private void t40MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t40MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t40MousePressed

    private void t39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t39ActionPerformed

    private void t39MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t39MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t39MousePressed

    private void t38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t38ActionPerformed

    private void t38MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t38MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t38MousePressed

    private void t37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t37ActionPerformed

    private void t37MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t37MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t37MousePressed

    private void t36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t36ActionPerformed

    private void t36MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t36MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t36MousePressed

    private void t35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t35ActionPerformed

    private void t35MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t35MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t35MousePressed

    private void t34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t34ActionPerformed

    private void t34MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t34MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t34MousePressed

    private void t33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t33ActionPerformed

    private void t33MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t33MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t33MousePressed

    private void t32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t32ActionPerformed

    private void t32MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t32MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t32MousePressed

    private void t31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t31ActionPerformed

    private void t31MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t31MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t31MousePressed

    private void t30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t30ActionPerformed

    private void t30MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t30MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t30MousePressed

    private void t29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t29ActionPerformed

    private void t29MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t29MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t29MousePressed

    private void t28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t28ActionPerformed

    private void t28MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t28MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t28MousePressed

    private void t27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t27ActionPerformed

    private void t27MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t27MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t27MousePressed

    private void t26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t26ActionPerformed

    private void t26MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t26MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t26MousePressed

    private void t23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t23ActionPerformed

    private void t23MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t23MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t23MousePressed

    private void t22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t22ActionPerformed

    private void t22MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t22MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t22MousePressed

    private void t21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t21ActionPerformed

    private void t21MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t21MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t21MousePressed

    private void t20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t20ActionPerformed

    private void t20MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t20MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t20MousePressed

    private void t19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t19ActionPerformed

    private void t19MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t19MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t19MousePressed

    private void t18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t18ActionPerformed

    private void t18MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t18MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t18MousePressed

    private void t17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t17ActionPerformed

    private void t17MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t17MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t17MousePressed

    private void t16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t16ActionPerformed

    private void t16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t16MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t16MousePressed

    private void t15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t15ActionPerformed

    private void t15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t15MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t15MousePressed

    private void t41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t41ActionPerformed

    private void t41MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t41MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t41MousePressed

    private void t14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t14ActionPerformed

    private void t14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t14MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t14MousePressed

    private void t13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t13ActionPerformed

    private void t13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t13MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t13MousePressed

    private void t11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t11ActionPerformed

    private void t11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t11MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t11MousePressed

    private void t10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t10ActionPerformed

    private void t10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t10MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t10MousePressed

    private void t9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t9ActionPerformed

    private void t9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t9MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t9MousePressed

    private void t8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t8ActionPerformed

    private void t8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t8MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t8MousePressed

    private void t7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t7ActionPerformed

    private void t7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t7MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t7MousePressed

    private void t6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t6ActionPerformed

    private void t6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t6MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t6MousePressed

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t5ActionPerformed

    private void t5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t5MousePressed

    private void t25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t25ActionPerformed

    private void t25MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t25MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t25MousePressed

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t4ActionPerformed

    private void t4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t4MousePressed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        Revisiones rv = new Revisiones(t1.getText(),t2.getText(),t3.getText(),t4.getText(), t5.getText(), t6.getText(), t7.getText(), t8.getText(), t9.getText(), t10.getText(), t11.getText(),t12.getText(), t13.getText(), t14.getText(), t15.getText(), t16.getText(), t17.getText(), t18.getText(), t19.getText(), t20.getText(), t21.getText(), t22.getText(), t23.getText(), t24.getText(), t25.getText(), t26.getText(), t27.getText(), t28.getText(), t29.getText(), t30.getText(), t31.getText(), t32.getText(), t33.getText(), t34.getText(), t35.getText(), t36.getText(), t37.getText(), t38.getText(), t39.getText(), t40.getText(), t41.getText(), t42.getText(), t43.getText());
        IRevisionesImpl irv = new IRevisionesImpl();
        irv.agregarRevisiones(rv);
        JOptionPane.showMessageDialog(this, "Acción Completada");

        Menu2B p1 = new Menu2B();
        p1.setSize(790, 570);
        p1.setLocation(0,0);

        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MousePressed

    private void t42MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t42MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t42MousePressed

    private void t42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t42ActionPerformed

    private void t2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2MousePressed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void t24MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t24MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t24MousePressed

    private void t24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t24ActionPerformed

    private void t1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_t1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1MousePressed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JSeparator jSeparator30;
    private javax.swing.JSeparator jSeparator31;
    private javax.swing.JSeparator jSeparator32;
    private javax.swing.JSeparator jSeparator33;
    private javax.swing.JSeparator jSeparator34;
    private javax.swing.JSeparator jSeparator35;
    private javax.swing.JSeparator jSeparator36;
    private javax.swing.JSeparator jSeparator37;
    private javax.swing.JSeparator jSeparator38;
    private javax.swing.JSeparator jSeparator39;
    private javax.swing.JSeparator jSeparator40;
    private javax.swing.JSeparator jSeparator41;
    private javax.swing.JSeparator jSeparator42;
    private javax.swing.JSeparator jSeparator43;
    private javax.swing.JSeparator jSeparator44;
    private javax.swing.JSeparator jSeparator45;
    private javax.swing.JSeparator jSeparator46;
    private javax.swing.JSeparator jSeparator47;
    private javax.swing.JSeparator jSeparator48;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator50;
    private javax.swing.JSeparator jSeparator51;
    private javax.swing.JSeparator jSeparator53;
    private javax.swing.JSeparator jSeparator54;
    private javax.swing.JSeparator jSeparator55;
    private javax.swing.JSeparator jSeparator56;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t10;
    private javax.swing.JTextField t11;
    private javax.swing.JTextField t12;
    private javax.swing.JTextField t13;
    private javax.swing.JTextField t14;
    private javax.swing.JTextField t15;
    private javax.swing.JTextField t16;
    private javax.swing.JTextField t17;
    private javax.swing.JTextField t18;
    private javax.swing.JTextField t19;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t20;
    private javax.swing.JTextField t21;
    private javax.swing.JTextField t22;
    private javax.swing.JTextField t23;
    private javax.swing.JTextField t24;
    private javax.swing.JTextField t25;
    private javax.swing.JTextField t26;
    private javax.swing.JTextField t27;
    private javax.swing.JTextField t28;
    private javax.swing.JTextField t29;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t30;
    private javax.swing.JTextField t31;
    private javax.swing.JTextField t32;
    private javax.swing.JTextField t33;
    private javax.swing.JTextField t34;
    private javax.swing.JTextField t35;
    private javax.swing.JTextField t36;
    private javax.swing.JTextField t37;
    private javax.swing.JTextField t38;
    private javax.swing.JTextField t39;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t40;
    private javax.swing.JTextField t41;
    private javax.swing.JTextField t42;
    private javax.swing.JTextField t43;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    // End of variables declaration//GEN-END:variables
}
